spring.application.name=algoarena-backend

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

gemini.model=gemini-3.5-flash-lite

spring.profiles.active=local
server.address=0.0.0.0
server.port=${PORT:8080}